{{- if .Values.httpgateway.enabled }}
{{- $fullname := include "plgd-hub.httpgateway.fullname" . }}
{{- $domainCrt := include "plgd-hub.httpgateway.domainCertName" . }}
{{- $port := .Values.httpgateway.port }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullname }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "plgd-hub.labels" . | nindent 4 }}
  annotations:
{{/*    kubernetes.io/ingress.class: "nginx"*/}}
    nginx.org/grpc-services: {{ $fullname | quote }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
  {{- with .Values.httpgateway.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
        - {{ include "plgd-hub.httpgateway.apiDomain" . | quote }}
        - {{ include "plgd-hub.httpgateway.uiDomain" . | quote }}
      secretName: {{ include "plgd-hub.httpgateway.domainCertName" . | quote }}
  rules:
  - host: {{ include "plgd-hub.httpgateway.uiDomain" . | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $fullname }}
            port:
              number: {{ $port }}
  - host: {{ include "plgd-hub.httpgateway.apiDomain" . | quote }}
    http:
      paths:
      {{- range  .Values.httpgateway.ingress.paths }}
      - path: {{ . }}
        pathType: Prefix
        backend:
          service:
            name: {{ $fullname }}
            port:
              number: {{ $port }}
      {{- end }}
{{- end }}
